CREATE TABLE PUBLIC.ELECTRIC_METERS
(ID UUID NOT NULL PRIMARY KEY,
ADD_YARD_LIGHTING BOOLEAN DEFAULT false NOT NULL,
NOTE VARCHAR(255));

CREATE TABLE PUBLIC.ELECTRIC_METERS_VALUES
(ID UUID NOT NULL PRIMARY KEY,
VALUE_DATE DATE NOT NULL,
METER_COUNT INTEGER NOT NULL,
NOTE VARCHAR(255),
ELECTRIC_METER_ID UUID NOT NULL);

CREATE TABLE PUBLIC.ELECTRIC_METERS_ACCRUALS
(ELECTRIC_METER_ID UUID NOT NULL PRIMARY KEY,
USER_ID UUID NOT NULL,
VALUE_ACCRUAL INTEGER NOT NULL,
NOTE VARCHAR(255),
ELECTRIC_METER_ID UUID NOT NULL);


ALTER TABLE PUBLIC.ELECTRIC_METERS_VALUES
ADD FOREIGN KEY (ELECTRIC_METER_ID) 
REFERENCES PUBLIC.ELECTRIC_METERS(ID);

ALTER TABLE PUBLIC.ELECTRIC_METERS_ACCRUALS
ADD FOREIGN KEY (ELECTRIC_METER_ID) 
REFERENCES PUBLIC.ELECTRIC_METERS(ID);

