INSERT INTO PUBLIC.ELECTRIC_METERS (ID, ADD_YARD_LIGHTING, NOTE)
VALUES (uuid(), true, 'note1');
INSERT INTO PUBLIC.ELECTRIC_METERS (ID, ADD_YARD_LIGHTING, NOTE)
VALUES (uuid(), true, 'note2');
INSERT INTO PUBLIC.ELECTRIC_METERS (ID, ADD_YARD_LIGHTING, NOTE)
VALUES (uuid(), false, 'note3');

INSERT INTO PUBLIC.ELECTRIC_METERS_VALUES (ELECTRIC_METER_ID, VALUE_DATE, METER_COUNT, NOTE)
VALUES (SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note1', '2018-09-27', 1234, 'note1');
INSERT INTO PUBLIC.ELECTRIC_METERS_VALUES (ELECTRIC_METER_ID, VALUE_DATE, METER_COUNT, NOTE)
VALUES (SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note2', '2018-09-25', 1222, 'note2');
INSERT INTO PUBLIC.ELECTRIC_METERS_VALUES (ELECTRIC_METER_ID, VALUE_DATE, METER_COUNT, NOTE)
VALUES (SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note3', '2018-09-24', 1333, null);


INSERT INTO PUBLIC.ELECTRIC_METERS_ACCRUALS (ELECTRIC_METER_ID, USER_ID, VALUE_ACCRUAL, NOTE)
VALUES (SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note1', uuid(), 1111, 'note1');

INSERT INTO PUBLIC.ELECTRIC_METERS_ACCRUALS (ELECTRIC_METER_ID, USER_ID, VALUE_ACCRUAL, NOTE)
VALUES (SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note2', uuid(), 2222, 'note2');

INSERT INTO PUBLIC.ELECTRIC_METERS_ACCRUALS (ELECTRIC_METER_ID, USER_ID, VALUE_ACCRUAL, NOTE)
VALUES (SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note3', uuid(), 3333, 'note3');