INSERT INTO PUBLIC.ELECTRIC_METERS (ID, ADD_YARD_LIGHTING, NOTE)
VALUES (uuid(), true, 'note1');
INSERT INTO PUBLIC.ELECTRIC_METERS (ID, ADD_YARD_LIGHTING, NOTE)
VALUES (uuid(), true, 'note2');
INSERT INTO PUBLIC.ELECTRIC_METERS (ID, ADD_YARD_LIGHTING, NOTE)
VALUES (uuid(), false, 'note3');


INSERT INTO PUBLIC.ELECTRIC_METERS_VALUES (ID, VALUE_DATE, METER_COUNT, NOTE, ELECTRIC_METER_ID)
VALUES (uuid(), '2018-09-27', 1234, 'note1', SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note1');

INSERT INTO PUBLIC.ELECTRIC_METERS_VALUES (ID, VALUE_DATE, METER_COUNT, NOTE, ELECTRIC_METER_ID)
VALUES (uuid(), '2018-09-25', 1222, 'note2', SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note2');

INSERT INTO PUBLIC.ELECTRIC_METERS_VALUES (ID, VALUE_DATE, METER_COUNT, NOTE, ELECTRIC_METER_ID)
VALUES (uuid(), '2018-09-24', 1333, null, SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note3');



INSERT INTO PUBLIC.ELECTRIC_METERS_ACCRUALS (ID, USER_ID, VALUE_ACCRUAL, NOTE, ELECTRIC_METER_ID)
VALUES (uuid(), uuid(), 1111, 'note1', SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note1');

INSERT INTO PUBLIC.ELECTRIC_METERS_ACCRUALS (ID, USER_ID, VALUE_ACCRUAL, NOTE, ELECTRIC_METER_ID)
VALUES (uuid(), uuid(), 2222, 'note2', SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note2');

INSERT INTO PUBLIC.ELECTRIC_METERS_ACCRUALS (ID, USER_ID, VALUE_ACCRUAL, NOTE, ELECTRIC_METER_ID)
VALUES (uuid(), uuid(), 3333, 'note3', SELECT ID FROM ELECTRIC_METERS WHERE NOTE = 'note3');

-- first row id: 2f517777-281a-4fe6-85e2-bc9831b2c9fa
-- second row id: da5c6136-63fb-4211-97b6-190e01e795c3 
-- third row id: 5351d8e2-c05a-496f-b95c-49d255339700